issue4 バーコードスキャンとWebページの実装
tou-kenichirou/flutter_study pull request #13
Opened 2023-06-23 03:58 UTC by tou-kenichirou

### 概要 
- バーコードのスキャン機能とその結果に応じてAmazonの商品ページを表示する機能を実装
  - isbn13をisbn10に変換する機能を利用して、URLに設定しています（参考：https://qiita.com/akiraindustry/items/2eba7c98d8fd9ce404c4）

https://github.com/tou-kenichirou/flutter_study/assets/59268832/9b685815-dff2-43ce-bb14-3f3d8822d6bc

2023-06-23 05:42 UTC, MinatoIshiwata commented on lib/extension/string_extension.dart
> +    }
reduce使ったらもう少し簡易化されないでしょうか？

2023-06-23 05:45 UTC, MinatoIshiwata requested changes
@tou-kenichirou 
1点コメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-06-26 06:14 UTC, tou-kenichirou commented
イメージ的にはこんな感じであってますかね？
再レビューお願いします

2023-06-27 05:46 UTC, MinatoIshiwata approved these changes
@tou-kenichirou 
イメージ通りです🙋
LGTM

2023-06-27 06:22 UTC, merged