Issue6 ニュースAPIを利用して、最新のニュースを表示するアプリを作成する
tou-kenichirou/flutter_study pull request #15
Opened 2023-07-13 06:08 UTC by tou-kenichirou

### 概要 
- NewsAPIを使って、最新のニュースを取得して表示する機能を実装
  - ニュースは横長で表示（左タイトル、右画像）
  - タップでWebviewを起動してニュースの本文を表示します
  - ロングタップでお気に入りに追加します
  - 左上のメニューからカテゴリ別、右上メニューから国別に表示できるようにしています
    - カテゴリ別表示やロングタップ方式、`impl`を使った実装は小林くんから情報をもらったのでそれを参考に実装しています
  - お気に入り画面でもタップでWebviewを起動してニュースの本文を表示します
  - お気に入りの削除は右上の編集ボタンをタップしてから記事ごとに選択削除します
  
- APIキーの管理について
  - `news_api_key.json`を作成し、その中にAPIキー情報を入れて管理しています
  -  AndroidStudioで実装しているので、`EditConfiguration`に`--dart-define-from-file=news_api_key.json`を指定して実行しています

- 補足
  - issue毎にフォルダ分けをする作業もこのPRで実施しているので、今回の実装とは関係ないファイルの変更があります

ニュース更新、スクロール

https://github.com/tou-kenichirou/flutter_study/assets/59268832/97ea3445-e0e9-4cac-b6df-2add23b5b184

お気に入り登録、削除

https://github.com/tou-kenichirou/flutter_study/assets/59268832/d1ed6ed3-d7ad-4ebb-b6ee-2bf6c01dffa6

2023-07-15 16:43 UTC, MinatoIshiwata commented on lib/issue_6/country_drawer.dart
スプレッド構文使うとスッキリしそうです🙋

2023-07-15 16:52 UTC, MinatoIshiwata commented on lib/issue_6/news_category_drawer.dart
スプレッド構文を利用したらもう少しスッキリしそうです🙋

2023-07-15 17:18 UTC, MinatoIshiwata requested changes
@tou-kenichirou 
何点かコメントしました🙋
ご確認のほどよろしくお願いいたします。

2023-07-18 01:11 UTC, tou-kenichirou commented
@MinatoIshiwata 
`final children`自体が不要になってシンプルになったと思います
再レビューお願いします

2023-07-19 17:17 UTC, MinatoIshiwata approved these changes
LGTM

2023-07-19 23:28 UTC, merged