issue1 カウントアップ機能実装
tou-kenichirou/flutter_study pull request #7
Opened 2023-06-02 02:15 UTC by tou-kenichirou

### 概要 
- カウントアップできるアプリを作成
  - 機能としては増える数字を表示するのと押すことができるボタンの設置のみ
    - 小回りが効きそうなボタンの下見も兼ねて、`ElevatedButton`を使用してます
  - `main.dart`に全処理を記述してます（これについて、今後の課題に問題がありそうだったら指摘お願いします）

動作確認

https://github.com/tou-kenichirou/flutter_study/assets/59268832/91bdc126-e452-41ef-9f45-b51bd75cd1eb

2023-06-02 02:19 UTC, tou-kenichirou commented
追加の条件の方未対応なので少々お待ちください

2023-06-02 02:34 UTC, tou-kenichirou commented
追加条件の対応まで完了しましたので、改めてレビューお願いします

2023-06-02 04:32 UTC, fujiki-yuya reviewed
@tou-kenichirou 
コメント追加してみました。🙇‍♂

2023-06-02 04:32 UTC, fujiki-yuya commented on lib/main.dart
> +            const SizedBox(height: 20),
SizedBoxなども8pxの倍数にするとデザイン的に良いかと思います🙇‍♂

2023-06-02 04:32 UTC, fujiki-yuya commented on lib/main.dart
> +class CountUpApp extends StatefulWidget {
このクラスは別ファイルに分けてもいいと思います。
その場合はCountUpScreenのような名前がよさそうです。🙇‍♂

2023-06-05 00:02 UTC, tou-kenichirou commented
処理の一部を別のファイルに移動と、デザインの微調整を行いました
再レビューお願いします

2023-06-05 00:45 UTC, fujiki-yuya commented on lib/count_up_screen.dart
> +    });
if文などのロジックはsetStateの外に書き、setStateではプロパティの変更だけを行うようにするほうが良いかと思います。🙇‍♂

2023-06-05 00:48 UTC, fujiki-yuya reviewed
@tou-kenichirou 
コメント追加しました。

2023-06-05 01:10 UTC, tou-kenichirou commented
こういうイメージであってるのかな？
再レビューお願いします

2023-06-05 01:28 UTC, fujiki-yuya commented
> こういうイメージであってるのかな？ 再レビューお願いします

はい、大丈夫です。その他の部分も自分は問題ないと思うので、あとは石渡さんから承認貰えればいいかと思います。🙇‍♂

2023-06-06 00:53 UTC, MinatoIshiwata commented on lib/count_up_screen.dart
> +      });
@tou-kenichirou 
こちらはsetState不要かと思います🙋

2023-06-06 00:54 UTC, MinatoIshiwata requested changes
@tou-kenichirou 
1箇所ご確認ください🙋
下記追加いただいてlintが通るように対応をお願いいたします。
https://medium.com/flutter-jp/analysis-b8dbb19d3978

2023-06-06 05:09 UTC, tou-kenichirou commented
指摘点及び、lintチェックで問題がない状態になるように対応しました
再レビューお願いします

2023-06-07 01:45 UTC, MinatoIshiwata approved these changes
LGTM

2023-06-07 04:19 UTC, merged